/**
 * The feature registry.
 *
 * One definition per feature, carrying everything four different subsystems
 * need so they can never drift apart:
 *
 *   1. the model — `inModel` selects the ordered vector fed to the GBDT and the
 *      three temporal agents;
 *   2. the XAI translation engine — `states` is the deterministic mapping matrix
 *      Phase 4 §1 mandates: discretise the raw value into a state, then hydrate
 *      an authoritative narrative template. No LLM is involved, and no maths
 *      happens on the client;
 *   3. InvestGPT — `aliases`, `sqlColumn` and `description` are what CSR-RAG
 *      retrieves over when pruning the schema;
 *   4. the UI — `label`, `unit` and `format` render the drill-down table.
 *
 * Adding a feature in one place therefore adds it everywhere, consistently.
 */

import type { FeatureGroup, FeatureUnit } from '@/lib/domain/types';

export interface FeatureState {
  /** Machine state label, e.g. STATE_OVERSOLD. */
  state: string;
  /** Inclusive lower bound; −Infinity for open. */
  min: number;
  /** Exclusive upper bound; +Infinity for open. */
  max: number;
  /**
   * Noun phrase describing what the state *is*, e.g.
   * "an exhaustion of sell-side pressure".
   */
  predicate: string;
  /**
   * Clause describing what it implies, e.g.
   * "indicating a high-probability mean reversion".
   */
  implication: string;
  /** Which way this state normally leans. */
  polarity: 'bullish' | 'bearish' | 'neutral';
}

export interface FeatureDefinition {
  key: string;
  label: string;
  /** ≤ 18 chars, for dense tables and chart axes. */
  shortLabel: string;
  group: FeatureGroup;
  unit: FeatureUnit;
  /** One sentence, shown in the schema explorer and on hover. */
  description: string;
  /** Plain-text formula, shown verbatim in the model card. */
  formula: string;
  /** Column in `v_equity_snapshot` that InvestGPT queries. */
  sqlColumn: string;
  /** Synonyms the NL→SQL retriever matches. */
  aliases: string[];
  /** True when the feature is part of the ordered model input vector. */
  inModel: boolean;
  /** Decimal places for display. */
  precision: number;
  /** Ordered state bands; the first whose [min, max) contains the value wins. */
  states: FeatureState[];
}

const B = (
  state: string,
  min: number,
  max: number,
  predicate: string,
  implication: string,
  polarity: FeatureState['polarity'],
): FeatureState => ({ state, min, max, predicate, implication, polarity });

/** Neutral filler band, used where the middle of the range carries no thesis. */
const NEUTRAL = (state: string, min: number, max: number, predicate: string): FeatureState =>
  B(state, min, max, predicate, 'offering no directional edge on its own', 'neutral');

// ─────────────────────────────────────────────────────────────────────────────
//  Definitions
// ─────────────────────────────────────────────────────────────────────────────

export const FEATURE_DEFINITIONS: FeatureDefinition[] = [
  // ── Momentum ──────────────────────────────────────────────────────────────
  {
    key: 'rsi_14',
    label: 'RSI (14)',
    shortLabel: 'RSI 14',
    group: 'momentum',
    unit: 'index_0_100',
    description: "Wilder's 14-period Relative Strength Index on closes.",
    formula: 'RSI = 100 − 100/(1 + avgGain₁₄/avgLoss₁₄), both Wilder-smoothed',
    sqlColumn: 'rsi_14',
    aliases: ['rsi', 'relative strength index', 'oversold', 'overbought'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_DEEPLY_OVERSOLD', -Infinity, 20, 'a capitulation in sell-side pressure', 'indicating a statistically stretched downside that historically snaps back', 'bullish'),
      B('STATE_OVERSOLD', 20, 32, 'an exhaustion of sell-side pressure', 'indicating a high-probability mean reversion', 'bullish'),
      B('STATE_WEAK', 32, 45, 'persistent but decelerating selling', 'leaving the tape without committed buyers', 'bearish'),
      NEUTRAL('STATE_BALANCED', 45, 55, 'a balanced order flow'),
      B('STATE_STRONG', 55, 68, 'sustained demand absorbing supply', 'confirming the prevailing advance', 'bullish'),
      B('STATE_OVERBOUGHT', 68, 80, 'buy-side saturation', 'raising the odds of a corrective pullback', 'bearish'),
      B('STATE_DEEPLY_OVERBOUGHT', 80, Infinity, 'a blow-off in buy-side pressure', 'indicating an unsustainable extension vulnerable to a sharp unwind', 'bearish'),
    ],
  },
  {
    key: 'rsi_2',
    label: 'RSI (2)',
    shortLabel: 'RSI 2',
    group: 'momentum',
    unit: 'index_0_100',
    description: 'Two-period RSI — a short-horizon exhaustion detector.',
    formula: 'RSI = 100 − 100/(1 + avgGain₂/avgLoss₂)',
    sqlColumn: 'rsi_2',
    aliases: ['rsi 2', 'short term rsi', 'two period rsi'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_EXTREME_LOW', -Infinity, 10, 'a two-day washout', 'setting up the highest-frequency reversion trade in the book', 'bullish'),
      B('STATE_LOW', 10, 30, 'short-horizon selling exhaustion', 'favouring a snap-back over the next one to three sessions', 'bullish'),
      NEUTRAL('STATE_MID', 30, 70, 'no short-horizon extreme'),
      B('STATE_HIGH', 70, 90, 'short-horizon buying exhaustion', 'favouring a pause or fade over the next one to three sessions', 'bearish'),
      B('STATE_EXTREME_HIGH', 90, Infinity, 'a two-day melt-up', 'flagging an over-extended tape prone to immediate give-back', 'bearish'),
    ],
  },
  {
    key: 'stoch_k_14',
    label: 'Stochastic %K (14)',
    shortLabel: 'Stoch %K',
    group: 'momentum',
    unit: 'index_0_100',
    description: 'Close position within the 14-bar high–low range, smoothed 3 bars.',
    formula: '%K = 100·(close − min(low,14)) / (max(high,14) − min(low,14)), SMA₃',
    sqlColumn: 'stoch_k_14',
    aliases: ['stochastic', 'stoch', '%k'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_OVERSOLD', -Infinity, 20, 'price pinned to the bottom of its recent range', 'where mean reversion is statistically favoured', 'bullish'),
      NEUTRAL('STATE_MID', 20, 80, 'price mid-range'),
      B('STATE_OVERBOUGHT', 80, Infinity, 'price pinned to the top of its recent range', 'where continuation requires fresh demand to appear', 'bearish'),
    ],
  },
  {
    key: 'williams_r_14',
    label: 'Williams %R (14)',
    shortLabel: 'Williams %R',
    group: 'momentum',
    unit: 'index_0_100',
    description: 'Inverted, unsmoothed stochastic on a −100…0 scale.',
    formula: '%R = −100·(max(high,14) − close) / (max(high,14) − min(low,14))',
    sqlColumn: 'williams_r_14',
    aliases: ['williams r', 'percent r'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_OVERSOLD', -Infinity, -80, 'a close at the extreme low of the range', 'a condition that historically precedes short-term bounces', 'bullish'),
      NEUTRAL('STATE_MID', -80, -20, 'a mid-range close'),
      B('STATE_OVERBOUGHT', -20, Infinity, 'a close at the extreme high of the range', 'a condition that historically precedes short-term fades', 'bearish'),
    ],
  },
  {
    key: 'roc_10',
    label: 'Rate of change (10)',
    shortLabel: 'ROC 10',
    group: 'momentum',
    unit: 'percent',
    description: 'Ten-bar percentage price change.',
    formula: 'ROC = 100·(closeₜ − closeₜ₋₁₀)/closeₜ₋₁₀',
    sqlColumn: 'roc_10',
    aliases: ['rate of change', 'roc', 'momentum'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_SHARP_DECLINE', -Infinity, -8, 'a sharp ten-bar decline', 'which either continues on momentum or reverts violently — regime dependent', 'bearish'),
      B('STATE_DECLINE', -8, -2, 'negative short-horizon momentum', 'weighing on the directional case', 'bearish'),
      NEUTRAL('STATE_FLAT', -2, 2, 'flat short-horizon momentum'),
      B('STATE_ADVANCE', 2, 8, 'positive short-horizon momentum', 'supporting continuation', 'bullish'),
      B('STATE_SHARP_ADVANCE', 8, Infinity, 'a sharp ten-bar advance', 'that demands confirmation from volume before it can be trusted', 'bullish'),
    ],
  },
  {
    key: 'roc_20',
    label: 'Rate of change (20)',
    shortLabel: 'ROC 20',
    group: 'momentum',
    unit: 'percent',
    description: 'Twenty-bar percentage price change.',
    formula: 'ROC = 100·(closeₜ − closeₜ₋₂₀)/closeₜ₋₂₀',
    sqlColumn: 'roc_20',
    aliases: ['20 day momentum', 'monthly momentum'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_DECLINE', -Infinity, -4, 'a negative one-month trajectory', 'placing the name in the losing tail of the cross-section', 'bearish'),
      NEUTRAL('STATE_FLAT', -4, 4, 'a flat one-month trajectory'),
      B('STATE_ADVANCE', 4, Infinity, 'a positive one-month trajectory', 'placing the name in the winning tail of the cross-section', 'bullish'),
    ],
  },
  {
    key: 'mfi_14',
    label: 'Money Flow Index (14)',
    shortLabel: 'MFI 14',
    group: 'momentum',
    unit: 'index_0_100',
    description: 'Volume-weighted RSI on typical price.',
    formula: 'MFI = 100 − 100/(1 + Σ positiveFlow₁₄ / Σ negativeFlow₁₄)',
    sqlColumn: 'mfi_14',
    aliases: ['money flow', 'mfi'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_OUTFLOW_EXHAUSTED', -Infinity, 20, 'exhausted dollar outflow', 'suggesting sellers have run out of size', 'bullish'),
      NEUTRAL('STATE_BALANCED', 20, 80, 'balanced dollar flow'),
      B('STATE_INFLOW_SATURATED', 80, Infinity, 'saturated dollar inflow', 'suggesting buyers are paying up into thinning supply', 'bearish'),
    ],
  },
  {
    key: 'cci_20',
    label: 'CCI (20)',
    shortLabel: 'CCI 20',
    group: 'momentum',
    unit: 'zscore',
    description: 'Commodity Channel Index — typical price deviation in mean-deviation units.',
    formula: 'CCI = (TP − SMA(TP,20)) / (0.015 · meanDeviation₂₀)',
    sqlColumn: 'cci_20',
    aliases: ['cci', 'commodity channel index'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_EXTREME_LOW', -Infinity, -150, 'an extreme statistical dislocation below fair value', 'where reversion probability is at its highest', 'bullish'),
      B('STATE_LOW', -150, -80, 'a dislocation below fair value', 'favouring reversion', 'bullish'),
      NEUTRAL('STATE_MID', -80, 80, 'price near its typical value'),
      B('STATE_HIGH', 80, 150, 'a dislocation above fair value', 'favouring reversion lower', 'bearish'),
      B('STATE_EXTREME_HIGH', 150, Infinity, 'an extreme statistical dislocation above fair value', 'where downside reversion probability is at its highest', 'bearish'),
    ],
  },
  {
    key: 'macd_hist',
    label: 'MACD histogram',
    shortLabel: 'MACD hist',
    group: 'momentum',
    unit: 'ratio',
    description: 'MACD line minus its signal line, normalised by price.',
    formula: '(EMA₁₂ − EMA₂₆ − EMA₉(EMA₁₂ − EMA₂₆)) / close',
    sqlColumn: 'macd_hist',
    aliases: ['macd', 'macd histogram', 'macd crossover'],
    inModel: true,
    precision: 4,
    states: [
      B('STATE_BEARISH_EXPANDING', -Infinity, -0.004, 'an expanding bearish momentum divergence', 'confirming that sellers retain control', 'bearish'),
      B('STATE_BEARISH', -0.004, -0.0005, 'a mild bearish momentum divergence', 'arguing against fresh long exposure', 'bearish'),
      NEUTRAL('STATE_NEUTRAL', -0.0005, 0.0005, 'momentum in equilibrium'),
      B('STATE_BULLISH', 0.0005, 0.004, 'a mild bullish momentum divergence', 'consistent with an early trend inflection', 'bullish'),
      B('STATE_BULLISH_EXPANDING', 0.004, Infinity, 'an expanding bullish momentum divergence', 'confirming that buyers retain control', 'bullish'),
    ],
  },
  {
    key: 'macd_signal_gap',
    label: 'MACD signal gap',
    shortLabel: 'MACD gap',
    group: 'momentum',
    unit: 'ratio',
    description: 'Distance from the MACD line to its signal, normalised by price — proximity to a crossover.',
    formula: '(MACD − signal) / close',
    sqlColumn: 'macd_signal_gap',
    aliases: ['impending macd crossover', 'macd signal'],
    inModel: true,
    precision: 4,
    states: [
      B('STATE_BEARISH_CROSS', -Infinity, -0.0008, 'a completed bearish crossover', 'with momentum already rolling over', 'bearish'),
      B('STATE_CROSS_IMMINENT', -0.0008, 0.0008, 'a crossover on the cusp of triggering', 'making the next one to two bars decisive', 'neutral'),
      B('STATE_BULLISH_CROSS', 0.0008, Infinity, 'a completed bullish crossover', 'with momentum already inflecting higher', 'bullish'),
    ],
  },
  {
    key: 'consecutive_closes',
    label: 'Consecutive closes',
    shortLabel: 'Consec closes',
    group: 'momentum',
    unit: 'count',
    description: 'Run length of consecutive higher (positive) or lower (negative) closes.',
    formula: 'signed run length of sign(closeₜ − closeₜ₋₁)',
    sqlColumn: 'consecutive_closes',
    aliases: ['down days', 'up days', 'streak', 'consecutive'],
    inModel: true,
    precision: 0,
    states: [
      B('STATE_LONG_DOWN_RUN', -Infinity, -4, 'a run of four or more consecutive lower closes', 'the setup the 5-day-bounce family of strategies is built on', 'bullish'),
      B('STATE_DOWN_RUN', -4, -1.5, 'a short run of lower closes', 'building reversion pressure', 'bullish'),
      NEUTRAL('STATE_MIXED', -1.5, 1.5, 'no meaningful run'),
      B('STATE_UP_RUN', 1.5, 4, 'a short run of higher closes', 'confirming demand', 'bullish'),
      B('STATE_LONG_UP_RUN', 4, Infinity, 'a run of four or more consecutive higher closes', 'statistically due for a pause', 'bearish'),
    ],
  },
  {
    key: 'close_location',
    label: 'Close location in range',
    shortLabel: 'Close loc',
    group: 'momentum',
    unit: 'ratio',
    description: 'Where the close sits in the bar range: 0 = at the low, 1 = at the high.',
    formula: '(close − low) / (high − low)',
    sqlColumn: 'close_location',
    aliases: ['close in range', 'bar strength'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_WEAK_CLOSE', -Infinity, 0.25, 'a close at the low of the bar', 'showing sellers held the tape into the bell', 'bearish'),
      NEUTRAL('STATE_MID_CLOSE', 0.25, 0.75, 'a mid-range close'),
      B('STATE_STRONG_CLOSE', 0.75, Infinity, 'a close at the high of the bar', 'showing buyers held the tape into the bell', 'bullish'),
    ],
  },

  // ── Trend ─────────────────────────────────────────────────────────────────
  {
    key: 'ema_20_50_spread',
    label: 'EMA 20/50 spread',
    shortLabel: 'EMA 20/50',
    group: 'trend',
    unit: 'percent',
    description: 'Fast/medium exponential moving-average spread as a percentage of price.',
    formula: '100·(EMA₂₀ − EMA₅₀)/close',
    sqlColumn: 'ema_20_50_spread',
    aliases: ['moving average spread', 'ema crossover', 'golden cross'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_BEAR_STACK', -Infinity, -1.5, 'a firmly bearish moving-average stack', 'with the intermediate trend against the position', 'bearish'),
      B('STATE_MILD_BEAR', -1.5, -0.2, 'a mildly bearish moving-average stack', 'keeping the intermediate trend unhelpful', 'bearish'),
      NEUTRAL('STATE_FLAT', -0.2, 0.2, 'moving averages in compression'),
      B('STATE_MILD_BULL', 0.2, 1.5, 'a mildly bullish moving-average stack', 'putting the intermediate trend behind the position', 'bullish'),
      B('STATE_BULL_STACK', 1.5, Infinity, 'a firmly bullish moving-average stack', 'with the intermediate trend strongly aligned', 'bullish'),
    ],
  },
  {
    key: 'ema_50_200_spread',
    label: 'EMA 50/200 spread',
    shortLabel: 'EMA 50/200',
    group: 'trend',
    unit: 'percent',
    description: 'Medium/long exponential moving-average spread — the primary trend filter.',
    formula: '100·(EMA₅₀ − EMA₂₀₀)/close',
    sqlColumn: 'ema_50_200_spread',
    aliases: ['long term trend', 'death cross', '200 day'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_PRIMARY_BEAR', -Infinity, -1, 'a primary downtrend', 'a regime in which long setups have materially lower base rates', 'bearish'),
      NEUTRAL('STATE_TRANSITION', -1, 1, 'a primary trend in transition'),
      B('STATE_PRIMARY_BULL', 1, Infinity, 'a primary uptrend', 'a regime in which long setups carry their highest base rates', 'bullish'),
    ],
  },
  {
    key: 'price_vs_ema20',
    label: 'Price vs EMA 20',
    shortLabel: 'vs EMA 20',
    group: 'trend',
    unit: 'percent',
    description: 'Extension of price above or below its 20-period EMA.',
    formula: '100·(close − EMA₂₀)/EMA₂₀',
    sqlColumn: 'price_vs_ema20',
    aliases: ['extension', 'distance from moving average', 'pullback'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_DEEP_DISCOUNT', -Infinity, -6, 'price stretched far below its anchor', 'a dislocation the OU model prices as reversion, not trend', 'bullish'),
      B('STATE_PULLBACK', -6, -1, 'a controlled pullback into the anchor', 'the classic continuation entry zone', 'bullish'),
      NEUTRAL('STATE_AT_ANCHOR', -1, 1, 'price sitting on its anchor'),
      B('STATE_EXTENDED', 1, 6, 'price extended above its anchor', 'reducing reward-to-risk on fresh entries', 'neutral'),
      B('STATE_OVER_EXTENDED', 6, Infinity, 'price stretched far above its anchor', 'where continuation entries carry poor reward-to-risk', 'bearish'),
    ],
  },
  {
    key: 'trend_slope_20',
    label: 'Regression slope (20)',
    shortLabel: 'Slope 20',
    group: 'trend',
    unit: 'percent',
    description: 'Least-squares slope of the last 20 closes, per bar, as a percentage of price.',
    formula: '100·β / mean(close), where β = Σ(x−x̄)(y−ȳ)/Σ(x−x̄)²',
    sqlColumn: 'trend_slope_20',
    aliases: ['trend slope', 'regression slope', 'linear trend'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_DOWN_SLOPE', -Infinity, -0.15, 'a statistically downward-sloping price path', 'with the fitted trend against the position', 'bearish'),
      NEUTRAL('STATE_FLAT_SLOPE', -0.15, 0.15, 'a statistically flat price path'),
      B('STATE_UP_SLOPE', 0.15, Infinity, 'a statistically upward-sloping price path', 'with the fitted trend supporting the position', 'bullish'),
    ],
  },
  {
    key: 'adx_14',
    label: 'ADX (14)',
    shortLabel: 'ADX 14',
    group: 'trend',
    unit: 'index_0_100',
    description: "Wilder's Average Directional Index — trend strength irrespective of direction.",
    formula: 'ADX = RMA₁₄(100·|+DI − −DI|/(+DI + −DI))',
    sqlColumn: 'adx_14',
    aliases: ['adx', 'trend strength', 'directional index'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_NO_TREND', -Infinity, 18, 'an absence of directional trend', 'the regime in which mean-reversion models outperform breakout models', 'neutral'),
      B('STATE_EMERGING_TREND', 18, 25, 'an emerging directional trend', 'not yet strong enough to trade as continuation', 'neutral'),
      B('STATE_TRENDING', 25, 40, 'a confirmed directional trend', 'the regime in which continuation setups carry their edge', 'bullish'),
      B('STATE_STRONG_TREND', 40, Infinity, 'an unusually strong directional trend', 'powerful but historically late-stage', 'neutral'),
    ],
  },
  {
    key: 'di_spread',
    label: '+DI − −DI',
    shortLabel: 'DI spread',
    group: 'trend',
    unit: 'index_0_100',
    description: 'Directional-indicator spread; the sign gives the trend direction.',
    formula: '+DI₁₄ − −DI₁₄',
    sqlColumn: 'di_spread',
    aliases: ['di spread', 'plus di minus di', 'directional movement'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_BEAR_CONTROL', -Infinity, -8, 'directional movement controlled by sellers', 'aligning the trend against the position', 'bearish'),
      NEUTRAL('STATE_CONTESTED', -8, 8, 'contested directional movement'),
      B('STATE_BULL_CONTROL', 8, Infinity, 'directional movement controlled by buyers', 'aligning the trend with the position', 'bullish'),
    ],
  },
  {
    key: 'aroon_osc',
    label: 'Aroon oscillator (25)',
    shortLabel: 'Aroon osc',
    group: 'trend',
    unit: 'index_0_100',
    description: 'Recency of the 25-bar high versus the 25-bar low.',
    formula: 'AroonUp − AroonDown, each = 100·(period − barsSinceExtreme)/period',
    sqlColumn: 'aroon_osc',
    aliases: ['aroon', 'aroon oscillator'],
    inModel: true,
    precision: 0,
    states: [
      B('STATE_LOWS_LEADING', -Infinity, -50, 'new lows arriving more recently than new highs', 'confirming distribution', 'bearish'),
      NEUTRAL('STATE_RANGE', -50, 50, 'highs and lows alternating'),
      B('STATE_HIGHS_LEADING', 50, Infinity, 'new highs arriving more recently than new lows', 'confirming accumulation', 'bullish'),
    ],
  },
  {
    key: 'supertrend_dir',
    label: 'Supertrend direction',
    shortLabel: 'Supertrend',
    group: 'trend',
    unit: 'signed_unit',
    description: 'ATR-band trailing-stop regime: +1 long, −1 short.',
    formula: 'sign flips when close crosses mid ± 3·ATR₁₀',
    sqlColumn: 'supertrend_dir',
    aliases: ['supertrend', 'trailing stop regime'],
    inModel: true,
    precision: 0,
    states: [
      B('STATE_SHORT_REGIME', -Infinity, 0, 'a trailing-stop regime flipped short', 'meaning a long entry fights the active stop structure', 'bearish'),
      B('STATE_LONG_REGIME', 0, Infinity, 'a trailing-stop regime flipped long', 'giving a long entry a defined structural invalidation', 'bullish'),
    ],
  },
  {
    key: 'dist_from_20d_high',
    label: 'Distance from 20-bar high',
    shortLabel: 'From 20d hi',
    group: 'trend',
    unit: 'percent',
    description: 'How far below the rolling 20-bar high the close sits.',
    formula: '100·(close − max(high,20))/max(high,20)',
    sqlColumn: 'dist_from_20d_high',
    aliases: ['near highs', 'breakout', '20 day high'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_DEEP_BELOW', -Infinity, -12, 'a deep drawdown from the recent high', 'requiring substantial repair before continuation is credible', 'bearish'),
      B('STATE_BELOW', -12, -3, 'a normal pullback from the recent high', 'the standard continuation entry window', 'neutral'),
      B('STATE_AT_HIGHS', -3, Infinity, 'price coiled at the recent high', 'a breakout-pending condition', 'bullish'),
    ],
  },
  {
    key: 'dist_from_252d_high',
    label: 'Distance from 52-week high',
    shortLabel: 'From 52w hi',
    group: 'trend',
    unit: 'percent',
    description: 'Drawdown from the 252-session high.',
    formula: '100·(close − max(high,252))/max(high,252)',
    sqlColumn: 'dist_from_252d_high',
    aliases: ['52 week high', 'yearly high', 'drawdown'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_BEAR_MARKET', -Infinity, -25, 'a drawdown of more than a quarter from the annual high', 'a condition that historically suppresses forward momentum returns', 'bearish'),
      B('STATE_CORRECTION', -25, -8, 'a correction from the annual high', 'leaving overhead supply to work through', 'neutral'),
      B('STATE_NEAR_52W_HIGH', -8, Infinity, 'price within reach of its annual high', 'the cross-sectional cohort with the strongest momentum persistence', 'bullish'),
    ],
  },
  {
    key: 'dist_from_20d_low',
    label: 'Distance from 20-bar low',
    shortLabel: 'From 20d lo',
    group: 'trend',
    unit: 'percent',
    description: 'How far above the rolling 20-bar low the close sits.',
    formula: '100·(close − min(low,20))/min(low,20)',
    sqlColumn: 'dist_from_20d_low',
    aliases: ['near lows', 'breakdown', '20 day low'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_AT_LOWS', -Infinity, 3, 'price pinned to the recent low', 'a breakdown-pending condition unless buyers step in', 'bearish'),
      NEUTRAL('STATE_ABOVE', 3, 15, 'price comfortably off the recent low'),
      B('STATE_WELL_ABOVE', 15, Infinity, 'price far above the recent low', 'confirming that the base held', 'bullish'),
    ],
  },

  // ── Volatility ────────────────────────────────────────────────────────────
  {
    key: 'atr_pct_14',
    label: 'ATR % (14)',
    shortLabel: 'ATR %',
    group: 'volatility',
    unit: 'percent',
    description: 'Average True Range as a percentage of price — the position-sizing denominator.',
    formula: '100·RMA₁₄(max(H−L, |H−C₋₁|, |L−C₋₁|)) / close',
    sqlColumn: 'atr_pct_14',
    aliases: ['atr', 'average true range', 'volatility'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_VERY_QUIET', -Infinity, 1, 'unusually compressed daily ranges', 'a coiled state that typically resolves with an expansion', 'neutral'),
      B('STATE_NORMAL', 1, 3, 'ordinary daily ranges', 'allowing standard stop placement', 'neutral'),
      B('STATE_ELEVATED', 3, 6, 'elevated daily ranges', 'requiring wider stops and smaller size for the same risk', 'neutral'),
      B('STATE_EXTREME', 6, Infinity, 'extreme daily ranges', 'a condition in which stop-outs on noise alone become likely', 'bearish'),
    ],
  },
  {
    key: 'realised_vol_20',
    label: 'Realised volatility (20)',
    shortLabel: 'RV 20',
    group: 'volatility',
    unit: 'percent',
    description: 'Annualised close-to-close realised volatility over 20 bars.',
    formula: '√252 · stdev(log returns, 20) · 100',
    sqlColumn: 'realised_vol_20',
    aliases: ['realized volatility', 'historical volatility', 'hv'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_LOW_VOL', -Infinity, 18, 'a low-volatility regime', 'where trend-following carries its highest Sharpe', 'neutral'),
      B('STATE_MID_VOL', 18, 35, 'a normal volatility regime', 'with no volatility-driven distortion to the setup', 'neutral'),
      B('STATE_HIGH_VOL', 35, 60, 'a high-volatility regime', 'in which static standard-deviation channels lag badly', 'neutral'),
      B('STATE_STRESS_VOL', 60, Infinity, 'a stress-level volatility regime', 'where correlations converge to one and diversification fails', 'bearish'),
    ],
  },
  {
    key: 'gk_vol_20',
    label: 'Garman–Klass volatility (20)',
    shortLabel: 'GK vol',
    group: 'volatility',
    unit: 'percent',
    description: 'OHLC-efficient volatility estimator — far lower variance than close-to-close.',
    formula: '√(252·mean(o² + ½(u−d)² − (2ln2−1)c²)) · 100, with o,u,d,c log ratios vs prior close/open',
    sqlColumn: 'gk_vol_20',
    aliases: ['garman klass', 'ohlc volatility', 'range volatility'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_LOW_VOL', -Infinity, 18, 'compressed intrabar volatility', 'confirming the low-volatility read from the close-to-close estimator', 'neutral'),
      NEUTRAL('STATE_MID_VOL', 18, 40, 'ordinary intrabar volatility'),
      B('STATE_HIGH_VOL', 40, Infinity, 'expanded intrabar volatility', 'showing genuine intraday risk the close-to-close estimator understates', 'neutral'),
    ],
  },
  {
    key: 'bb_width_20',
    label: 'Bollinger width (20, 2σ)',
    shortLabel: 'BB width',
    group: 'volatility',
    unit: 'ratio',
    description: 'Bollinger band width relative to the mid — the classic squeeze gauge.',
    formula: '(upper − lower)/middle, upper/lower = SMA₂₀ ± 2·σ₂₀',
    sqlColumn: 'bb_width_20',
    aliases: ['bollinger width', 'bollinger bands', 'squeeze'],
    inModel: true,
    precision: 4,
    states: [
      B('STATE_SQUEEZE', -Infinity, 0.04, 'a volatility squeeze', 'a compressed state that historically resolves with a directional expansion', 'neutral'),
      NEUTRAL('STATE_NORMAL', 0.04, 0.14, 'ordinary band width'),
      B('STATE_EXPANDED', 0.14, Infinity, 'fully expanded bands', 'a late-stage volatility state where the static channel is at its least informative', 'neutral'),
    ],
  },
  {
    key: 'bb_percent_b',
    label: 'Bollinger %B',
    shortLabel: '%B',
    group: 'volatility',
    unit: 'ratio',
    description: 'Position of price within the Bollinger channel; 0 = lower band, 1 = upper.',
    formula: '(close − lower)/(upper − lower)',
    sqlColumn: 'bb_percent_b',
    aliases: ['percent b', 'bollinger position', 'band position'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_BELOW_LOWER', -Infinity, 0, 'a close outside the lower band', 'a two-sigma statistical dislocation', 'bullish'),
      B('STATE_LOWER_ZONE', 0, 0.25, 'a close in the lower quarter of the channel', 'the reversion entry zone', 'bullish'),
      NEUTRAL('STATE_MID_ZONE', 0.25, 0.75, 'a close in the middle of the channel'),
      B('STATE_UPPER_ZONE', 0.75, 1, 'a close in the upper quarter of the channel', 'where continuation requires fresh demand', 'neutral'),
      B('STATE_ABOVE_UPPER', 1, Infinity, 'a close outside the upper band', 'a two-sigma extension that either signals a breakout or an exhaustion', 'neutral'),
    ],
  },
  {
    key: 'squeeze_pct',
    label: 'Squeeze percentile (120)',
    shortLabel: 'Squeeze %ile',
    group: 'volatility',
    unit: 'probability',
    description: 'Percentile of the current band width within its own 120-bar history.',
    formula: 'rank(bbWidthₜ) / n over the last 120 bars',
    sqlColumn: 'squeeze_pct',
    aliases: ['squeeze percentile', 'volatility percentile', 'compression'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_EXTREME_SQUEEZE', -Infinity, 0.1, 'band width in the bottom decile of its own history', 'the highest-probability precursor to a volatility expansion', 'neutral'),
      B('STATE_SQUEEZE', 0.1, 0.3, 'band width in the lower third of its own history', 'a compression building toward expansion', 'neutral'),
      NEUTRAL('STATE_NORMAL', 0.3, 0.8, 'typical band width for this name'),
      B('STATE_EXPANDED', 0.8, Infinity, 'band width in the top fifth of its own history', 'a state that historically mean-reverts toward compression', 'neutral'),
    ],
  },
  {
    key: 'keltner_percent_b',
    label: 'Keltner %B',
    shortLabel: 'Keltner %B',
    group: 'volatility',
    unit: 'ratio',
    description: 'Position within the ATR-based Keltner channel.',
    formula: '(close − (EMA₂₀ − 2·ATR₁₀)) / (4·ATR₁₀)',
    sqlColumn: 'keltner_percent_b',
    aliases: ['keltner', 'keltner channel'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_BELOW', -Infinity, 0.15, 'price below the ATR channel', 'a volatility-adjusted dislocation lower', 'bullish'),
      NEUTRAL('STATE_INSIDE', 0.15, 0.85, 'price inside the ATR channel'),
      B('STATE_ABOVE', 0.85, Infinity, 'price above the ATR channel', 'a volatility-adjusted extension higher', 'neutral'),
    ],
  },
  {
    key: 'vol_ratio_5_20',
    label: 'Volatility ratio 5/20',
    shortLabel: 'Vol 5/20',
    group: 'volatility',
    unit: 'ratio',
    description: 'Short-horizon volatility relative to the 20-bar baseline.',
    formula: 'stdev(returns,5) / stdev(returns,20)',
    sqlColumn: 'vol_ratio_5_20',
    aliases: ['volatility ratio', 'vol expansion', 'vol contraction'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_CONTRACTING', -Infinity, 0.7, 'contracting short-horizon volatility', 'the coil that precedes expansion', 'neutral'),
      NEUTRAL('STATE_STABLE', 0.7, 1.4, 'stable volatility'),
      B('STATE_EXPANDING', 1.4, Infinity, 'expanding short-horizon volatility', 'the heteroskedastic shift that the Kalman gain re-weights against immediately', 'neutral'),
    ],
  },
  {
    key: 'gap_pct',
    label: 'Overnight gap %',
    shortLabel: 'Gap %',
    group: 'volatility',
    unit: 'percent',
    description: 'Session open relative to the prior close.',
    formula: '100·(open − prevClose)/prevClose',
    sqlColumn: 'gap_pct',
    aliases: ['gap', 'overnight gap', 'gap up', 'gap down'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_GAP_DOWN_LARGE', -Infinity, -3, 'a large downside gap', 'the setup for a gap-fill reversion when the news is not structural', 'bullish'),
      B('STATE_GAP_DOWN', -3, -0.75, 'a modest downside gap', 'leaving unfilled supply overhead', 'bearish'),
      NEUTRAL('STATE_NO_GAP', -0.75, 0.75, 'no meaningful gap'),
      B('STATE_GAP_UP', 0.75, 3, 'a modest upside gap', 'leaving unfilled demand below', 'bullish'),
      B('STATE_GAP_UP_LARGE', 3, Infinity, 'a large upside gap', 'a continuation-or-fade decision that resolves in the first thirty minutes', 'neutral'),
    ],
  },

  // ── Mean reversion (OU / Kalman) ──────────────────────────────────────────
  {
    key: 'ou_zscore',
    label: 'OU z-score',
    shortLabel: 'OU z',
    group: 'meanreversion',
    unit: 'zscore',
    description: 'Deviation from the Ornstein–Uhlenbeck equilibrium, in stationary sigmas.',
    formula: '(x − μ̂)/σ̂_eq, σ̂_eq = σ̂/√(2θ̂), MLE-calibrated',
    sqlColumn: 'ou_zscore',
    aliases: ['ou z score', 'mean reversion z', 'ornstein uhlenbeck', 'spread z'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_EXTREME_BELOW', -Infinity, -2.5, 'a two-and-a-half-sigma dislocation below continuous-time equilibrium', 'the highest-conviction reversion state the OU model produces', 'bullish'),
      B('STATE_BELOW', -2.5, -1.2, 'a dislocation below continuous-time equilibrium', 'giving the reversion trajectory a positive expectation', 'bullish'),
      NEUTRAL('STATE_AT_EQUILIBRIUM', -1.2, 1.2, 'price at its continuous-time equilibrium'),
      B('STATE_ABOVE', 1.2, 2.5, 'a dislocation above continuous-time equilibrium', 'giving the reversion trajectory a negative expectation', 'bearish'),
      B('STATE_EXTREME_ABOVE', 2.5, Infinity, 'a two-and-a-half-sigma dislocation above continuous-time equilibrium', 'the highest-conviction downside reversion state the OU model produces', 'bearish'),
    ],
  },
  {
    key: 'ou_half_life',
    label: 'OU half-life',
    shortLabel: 'Half-life',
    group: 'meanreversion',
    unit: 'bars',
    description: 'Bars for half of a shock to decay under the calibrated OU process.',
    formula: 'ln2 / θ̂',
    sqlColumn: 'ou_half_life',
    aliases: ['half life', 'reversion speed', 'theta'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_FAST_REVERSION', -Infinity, 5, 'an extremely fast reversion half-life', 'meaning any dislocation should resolve within a handful of bars', 'neutral'),
      B('STATE_TRADEABLE_REVERSION', 5, 25, 'a tradeable reversion half-life', 'matching the horizon this signal is scored over', 'bullish'),
      B('STATE_SLOW_REVERSION', 25, 90, 'a slow reversion half-life', 'making the reversion thesis a position trade rather than a swing', 'neutral'),
      B('STATE_NO_REVERSION', 90, Infinity, 'a half-life too long to trade', 'so the series is effectively a random walk and reversion carries no edge', 'neutral'),
    ],
  },
  {
    key: 'ou_theta',
    label: 'OU θ (reversion rate)',
    shortLabel: 'OU θ',
    group: 'meanreversion',
    unit: 'ratio',
    description: 'Maximum-likelihood mean-reversion rate of the continuous-time process.',
    formula: 'θ̂ = −ln(b̂)/Δt, b̂ from the closed-form AR(1) MLE',
    sqlColumn: 'ou_theta',
    aliases: ['theta', 'reversion rate', 'kappa'],
    inModel: true,
    precision: 4,
    states: [
      B('STATE_WEAK', -Infinity, 0.02, 'negligible measured reversion force', 'so the OU block should be discounted for this name', 'neutral'),
      NEUTRAL('STATE_MODERATE', 0.02, 0.15, 'a moderate measured reversion force'),
      B('STATE_STRONG', 0.15, Infinity, 'a strong measured reversion force', 'making the OU block the dominant driver for this name', 'bullish'),
    ],
  },
  {
    key: 'ou_reversion_prob',
    label: 'OU reversion probability',
    shortLabel: 'Rev prob',
    group: 'meanreversion',
    unit: 'probability',
    description: 'Probability the process is closer to equilibrium after the signal horizon.',
    formula: 'P(|X_{t+τ} − μ| < |X_t − μ|) under the exact Gaussian OU transition density',
    sqlColumn: 'ou_reversion_prob',
    aliases: ['reversion probability', 'mean reversion odds'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_UNLIKELY', -Infinity, 0.45, 'a below-even chance of reverting over the horizon', 'undermining any reversion-based thesis', 'bearish'),
      NEUTRAL('STATE_COIN_FLIP', 0.45, 0.58, 'roughly even reversion odds'),
      B('STATE_LIKELY', 0.58, 0.72, 'favourable reversion odds', 'giving the trajectory a positive expected value', 'bullish'),
      B('STATE_HIGHLY_LIKELY', 0.72, Infinity, 'strongly favourable reversion odds', 'the condition the continuous-time model is built to isolate', 'bullish'),
    ],
  },
  {
    key: 'kalman_innovation_z',
    label: 'Kalman innovation z',
    shortLabel: 'Innov z',
    group: 'meanreversion',
    unit: 'zscore',
    description: 'Standardised one-step-ahead measurement residual from the Kalman filter.',
    formula: 'ỹ / √S, S = H·P⁻·Hᵀ + R with R adapted online',
    sqlColumn: 'kalman_innovation_z',
    aliases: ['kalman innovation', 'residual z', 'surprise'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_LARGE_NEGATIVE_SURPRISE', -Infinity, -2, 'a large negative surprise against the filtered state', 'a dislocation the adaptive filter re-weights against immediately', 'bullish'),
      NEUTRAL('STATE_IN_LINE', -2, 2, 'a print in line with the filtered state'),
      B('STATE_LARGE_POSITIVE_SURPRISE', 2, Infinity, 'a large positive surprise against the filtered state', 'an extension the adaptive filter treats as signal rather than noise', 'neutral'),
    ],
  },
  {
    key: 'kalman_band_pos',
    label: 'Kalman band position',
    shortLabel: 'Kalman pos',
    group: 'meanreversion',
    unit: 'ratio',
    description: 'Position inside the dynamic Kalman innovation band; 0 = lower, 1 = upper.',
    formula: '(close − (level − 2√S)) / (4√S)',
    sqlColumn: 'kalman_band_pos',
    aliases: ['kalman band', 'innovation band', 'dynamic channel'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_AT_LOWER', -Infinity, 0.2, 'price at the floor of the adaptive channel', 'a level that widens with realised volatility instead of lagging it', 'bullish'),
      NEUTRAL('STATE_MID_CHANNEL', 0.2, 0.8, 'price mid-channel'),
      B('STATE_AT_UPPER', 0.8, Infinity, 'price at the ceiling of the adaptive channel', 'a level that widens with realised volatility instead of lagging it', 'bearish'),
    ],
  },
  {
    key: 'kalman_slope_bps',
    label: 'Kalman slope',
    shortLabel: 'Kalman slope',
    group: 'meanreversion',
    unit: 'bps',
    description: 'Filtered local trend of fair value, in basis points per bar.',
    formula: '10 000 · slope / level, slope from the local-level+trend state',
    sqlColumn: 'kalman_slope_bps',
    aliases: ['kalman slope', 'filtered trend', 'state trend'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_FALLING_FAIR_VALUE', -Infinity, -8, 'falling filtered fair value', 'meaning the state-space estimate itself is trending down', 'bearish'),
      NEUTRAL('STATE_FLAT_FAIR_VALUE', -8, 8, 'flat filtered fair value'),
      B('STATE_RISING_FAIR_VALUE', 8, Infinity, 'rising filtered fair value', 'meaning the state-space estimate itself is trending up', 'bullish'),
    ],
  },
  {
    key: 'kalman_forecast_sigma_bps',
    label: 'Kalman forecast σ',
    shortLabel: 'Forecast σ',
    group: 'meanreversion',
    unit: 'bps',
    description: 'One-step forecast standard deviation — live model uncertainty.',
    formula: '10 000·√S / level',
    sqlColumn: 'kalman_forecast_sigma_bps',
    aliases: ['forecast sigma', 'model uncertainty', 'kalman uncertainty'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_CONFIDENT', -Infinity, 40, 'a tight forecast distribution', 'so the filtered state can be trusted for execution timing', 'neutral'),
      NEUTRAL('STATE_NORMAL_UNCERTAINTY', 40, 120, 'ordinary forecast uncertainty'),
      B('STATE_UNCERTAIN', 120, Infinity, 'a wide forecast distribution', 'a state in which the filter itself signals low confidence', 'bearish'),
    ],
  },
  {
    key: 'vwap_deviation_bps',
    label: 'VWAP deviation',
    shortLabel: 'vs VWAP',
    group: 'meanreversion',
    unit: 'bps',
    description: 'Distance from session VWAP, in basis points — the institutional benchmark.',
    formula: '10 000·(close − VWAP)/VWAP',
    sqlColumn: 'vwap_deviation_bps',
    aliases: ['vwap', 'vwap deviation', 'above vwap', 'below vwap'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_BELOW_VWAP', -Infinity, -60, 'price trading well below session VWAP', 'meaning the average institutional buyer today is underwater', 'bullish'),
      NEUTRAL('STATE_AT_VWAP', -60, 60, 'price at session VWAP'),
      B('STATE_ABOVE_VWAP', 60, Infinity, 'price trading well above session VWAP', 'meaning the average institutional buyer today is in profit and may defend', 'bullish'),
    ],
  },

  // ── Microstructure ────────────────────────────────────────────────────────
  {
    key: 'mlofi_intent',
    label: 'MLOFI directional intent',
    shortLabel: 'MLOFI intent',
    group: 'microstructure',
    unit: 'signed_unit',
    description: 'PCA-filtered multi-level order-flow imbalance, squashed to [−1, 1].',
    formula: 'tanh(z_PC1/2), z from the scale-only projection of MLOFI onto its first eigenvector',
    sqlColumn: 'mlofi_intent',
    aliases: ['order flow imbalance', 'mlofi', 'market maker intent', 'order flow'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_HEAVY_SELLING', -Infinity, -0.5, 'sustained multi-level sell-side order-flow imbalance', 'showing market makers absorbing on the offer across the book', 'bearish'),
      B('STATE_SELLING', -0.5, -0.15, 'mild sell-side order-flow imbalance', 'a headwind to any long entry', 'bearish'),
      NEUTRAL('STATE_BALANCED', -0.15, 0.15, 'balanced order flow across the book'),
      B('STATE_BUYING', 0.15, 0.5, 'mild buy-side order-flow imbalance', 'a tailwind to a long entry', 'bullish'),
      B('STATE_HEAVY_BUYING', 0.5, Infinity, 'sustained multi-level buy-side order-flow imbalance', 'the microstructural footprint of institutional accumulation', 'bullish'),
    ],
  },
  {
    key: 'mlofi_pc1_z',
    label: 'MLOFI PC1 z-score',
    shortLabel: 'MLOFI z',
    group: 'microstructure',
    unit: 'zscore',
    description: 'Net order-flow projection on the first principal component, as a t-statistic.',
    formula: 'Σₖ tₖ / (sd(t)·√n), tₖ = Σₘ wₘ·OFI^m_k/σₘ',
    sqlColumn: 'mlofi_pc1_z',
    aliases: ['mlofi z score', 'order flow z', 'pca order flow'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_SIGNIFICANT_SELLING', -Infinity, -1.6, 'statistically significant net sell-side flow', 'beyond what book noise explains', 'bearish'),
      NEUTRAL('STATE_INSIGNIFICANT', -1.6, 1.6, 'net flow within the noise band'),
      B('STATE_SIGNIFICANT_BUYING', 1.6, Infinity, 'statistically significant net buy-side flow', 'beyond what book noise explains', 'bullish'),
    ],
  },
  {
    key: 'mlofi_pc1_variance',
    label: 'MLOFI PC1 explained variance',
    shortLabel: 'PC1 var',
    group: 'microstructure',
    unit: 'probability',
    description: 'Share of order-book variance captured by the first principal component.',
    formula: 'λ₁ / Σλ of the standardised MLOFI covariance matrix',
    sqlColumn: 'mlofi_pc1_variance',
    aliases: ['pc1 variance', 'book dimensionality', 'explained variance'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_MULTI_FACTOR', -Infinity, 0.35, 'a book whose flow is genuinely multi-dimensional', 'so the single-factor intent reading should be discounted', 'neutral'),
      NEUTRAL('STATE_MIXED', 0.35, 0.6, 'a partially one-dimensional book'),
      B('STATE_ONE_FACTOR', 0.6, Infinity, 'a book whose flow collapses onto one factor', 'making the PCA-filtered intent reading unusually reliable', 'neutral'),
    ],
  },
  {
    key: 'queue_imbalance',
    label: 'Level-1 queue imbalance',
    shortLabel: 'Queue imb',
    group: 'microstructure',
    unit: 'signed_unit',
    description: 'Top-of-book size imbalance.',
    formula: '(bidSize − askSize)/(bidSize + askSize)',
    sqlColumn: 'queue_imbalance',
    aliases: ['queue imbalance', 'bid ask imbalance', 'top of book'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_ASK_HEAVY', -Infinity, -0.3, 'a top of book stacked on the offer', 'the short-horizon predictor of a downtick', 'bearish'),
      NEUTRAL('STATE_BALANCED', -0.3, 0.3, 'a balanced top of book'),
      B('STATE_BID_HEAVY', 0.3, Infinity, 'a top of book stacked on the bid', 'the short-horizon predictor of an uptick', 'bullish'),
    ],
  },
  {
    key: 'depth_imbalance',
    label: 'Depth imbalance (10)',
    shortLabel: 'Depth imb',
    group: 'microstructure',
    unit: 'signed_unit',
    description: 'Size imbalance across ten book levels.',
    formula: '(Σbid − Σask)/(Σbid + Σask) over ten levels',
    sqlColumn: 'depth_imbalance',
    aliases: ['depth imbalance', 'book imbalance', 'liquidity imbalance'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_ASK_HEAVY', -Infinity, -0.25, 'resting liquidity concentrated on the offer', 'meaning any rally must consume real supply', 'bearish'),
      NEUTRAL('STATE_BALANCED', -0.25, 0.25, 'symmetric resting liquidity'),
      B('STATE_BID_HEAVY', 0.25, Infinity, 'resting liquidity concentrated on the bid', 'giving a decline real support to work through', 'bullish'),
    ],
  },
  {
    key: 'spread_bps',
    label: 'Quoted spread',
    shortLabel: 'Spread',
    group: 'microstructure',
    unit: 'bps',
    description: 'Bid–ask spread in basis points of the mid.',
    formula: '10 000·(ask − bid)/mid',
    sqlColumn: 'spread_bps',
    aliases: ['spread', 'bid ask spread', 'transaction cost'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_TIGHT', -Infinity, 3, 'an institutionally tight spread', 'so execution cost is negligible relative to the expected move', 'neutral'),
      NEUTRAL('STATE_NORMAL', 3, 12, 'an ordinary spread'),
      B('STATE_WIDE', 12, 40, 'a wide spread', 'materially eroding the expected value of a short-horizon trade', 'bearish'),
      B('STATE_VERY_WIDE', 40, Infinity, 'a punitive spread', 'making this name unsuitable for tactical execution at size', 'bearish'),
    ],
  },
  {
    key: 'roll_spread_bps',
    label: 'Roll effective spread',
    shortLabel: 'Roll spread',
    group: 'microstructure',
    unit: 'bps',
    description: 'Effective spread inferred from serial covariance of price changes.',
    formula: '10 000·2√(−cov(Δpₜ, Δpₜ₋₁))/price',
    sqlColumn: 'roll_spread_bps',
    aliases: ['roll spread', 'effective spread', 'bid ask bounce'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_LOW_BOUNCE', -Infinity, 6, 'little bid–ask bounce in the tape', 'so observed price changes are mostly information, not noise', 'neutral'),
      NEUTRAL('STATE_NORMAL_BOUNCE', 6, 25, 'ordinary bid–ask bounce'),
      B('STATE_HIGH_BOUNCE', 25, Infinity, 'heavy bid–ask bounce', 'meaning much of the observed move is microstructure noise, not signal', 'bearish'),
    ],
  },
  {
    key: 'kyle_lambda',
    label: "Kyle's lambda",
    shortLabel: 'Kyle λ',
    group: 'microstructure',
    unit: 'ratio',
    description: 'Price impact per unit of signed volume — the depth of the market.',
    formula: 'λ = Σ(signedVolume·Δp)/Σ(signedVolume²)',
    sqlColumn: 'kyle_lambda',
    aliases: ['kyle lambda', 'price impact', 'market impact'],
    inModel: true,
    precision: 8,
    states: [
      B('STATE_DEEP', -Infinity, 0.000002, 'a deep market that absorbs size', 'so a position can be built without moving the print', 'bullish'),
      NEUTRAL('STATE_NORMAL_DEPTH', 0.000002, 0.00002, 'ordinary market depth'),
      B('STATE_THIN', 0.00002, Infinity, 'a thin market where size moves price', 'so realised slippage will exceed the modelled cost', 'bearish'),
    ],
  },
  {
    key: 'amihud_illiq',
    label: 'Amihud illiquidity',
    shortLabel: 'Amihud',
    group: 'microstructure',
    unit: 'ratio',
    description: 'Mean absolute return per million dollars of volume.',
    formula: '10⁶·mean(|r| / dollarVolume)',
    sqlColumn: 'amihud_illiq',
    aliases: ['amihud', 'illiquidity', 'liquidity measure'],
    inModel: true,
    precision: 4,
    states: [
      B('STATE_LIQUID', -Infinity, 0.05, 'high dollar liquidity', 'supporting institutional size without impact', 'bullish'),
      NEUTRAL('STATE_NORMAL_LIQUIDITY', 0.05, 0.5, 'ordinary dollar liquidity'),
      B('STATE_ILLIQUID', 0.5, Infinity, 'poor dollar liquidity', 'a name where the 5%-of-ADV limiter will bind before a full position is filled', 'bearish'),
    ],
  },
  {
    key: 'vpin',
    label: 'VPIN',
    shortLabel: 'VPIN',
    group: 'microstructure',
    unit: 'probability',
    description: 'Volume-synchronised probability of informed trading.',
    formula: 'mean over buckets of |buyVol − sellVol| / bucketVolume',
    sqlColumn: 'vpin',
    aliases: ['vpin', 'informed trading', 'toxicity', 'flow toxicity'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_BENIGN_FLOW', -Infinity, 0.25, 'benign, two-sided order flow', 'so adverse selection risk is low', 'bullish'),
      NEUTRAL('STATE_NORMAL_FLOW', 0.25, 0.45, 'ordinary flow toxicity'),
      B('STATE_TOXIC_FLOW', 0.45, Infinity, 'toxic, one-sided order flow', 'the microstructural precursor to a liquidity-driven dislocation', 'bearish'),
    ],
  },
  {
    key: 'micro_mid_divergence_bps',
    label: 'Micro-price divergence',
    shortLabel: 'Micro div',
    group: 'microstructure',
    unit: 'bps',
    description: 'Size-weighted micro-price minus the arithmetic mid.',
    formula: '10 000·(microPrice − mid)/mid, microPrice = (bid·askSize + ask·bidSize)/(bidSize + askSize)',
    sqlColumn: 'micro_mid_divergence_bps',
    aliases: ['micro price', 'weighted mid', 'fair value divergence'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_MICRO_BELOW', -Infinity, -1.5, 'a micro-price below the arithmetic mid', 'the next tick is more likely down than up', 'bearish'),
      NEUTRAL('STATE_MICRO_ALIGNED', -1.5, 1.5, 'a micro-price aligned with the mid'),
      B('STATE_MICRO_ABOVE', 1.5, Infinity, 'a micro-price above the arithmetic mid', 'the next tick is more likely up than down', 'bullish'),
    ],
  },
  {
    key: 'book_resilience',
    label: 'Book resilience',
    shortLabel: 'Resilience',
    group: 'microstructure',
    unit: 'ratio',
    description: 'Slope of cumulative depth against distance from the mid.',
    formula: 'β of cumulativeDepth on |distanceFromMid| across the modelled levels',
    sqlColumn: 'book_resilience',
    aliases: ['book resilience', 'depth slope', 'book shape'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_FRAGILE', -Infinity, 500, 'a fragile book that thins quickly away from the touch', 'so a sweep would gap the price', 'bearish'),
      NEUTRAL('STATE_NORMAL_SHAPE', 500, 5000, 'an ordinary book shape'),
      B('STATE_RESILIENT', 5000, Infinity, 'a resilient book with depth stacked behind the touch', 'so a sweep would be absorbed rather than gap the price', 'bullish'),
    ],
  },

  // ── Volatility skew (SABR) ────────────────────────────────────────────────
  {
    key: 'iv_atm_30d',
    label: 'ATM implied vol (30d)',
    shortLabel: 'ATM IV',
    group: 'skew',
    unit: 'percent',
    description: 'At-the-money implied volatility from the calibrated SABR surface.',
    formula: 'σ_B(F, F, 30/365) under Hagan with fitted (α, β=0.5, ρ, ν)',
    sqlColumn: 'iv_atm_30d',
    aliases: ['implied volatility', 'iv', 'atm iv', 'option volatility'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_CHEAP_VOL', -Infinity, 20, 'cheap option volatility', 'so hedging or defining risk with options costs little', 'neutral'),
      NEUTRAL('STATE_FAIR_VOL', 20, 45, 'fairly priced option volatility'),
      B('STATE_RICH_VOL', 45, Infinity, 'richly priced option volatility', 'showing the options market is pricing a large forthcoming move', 'neutral'),
    ],
  },
  {
    key: 'rr25_30d',
    label: '25Δ risk reversal (30d)',
    shortLabel: 'RR 25Δ',
    group: 'skew',
    unit: 'volpoints',
    description: 'σ(25Δ call) − σ(25Δ put) — how institutions price the two tails.',
    formula: 'RR₂₅ = σ_B(K₂₅c) − σ_B(K₂₅p), strikes solved so smile-consistent Δ = ±0.25',
    sqlColumn: 'rr25_30d',
    aliases: ['risk reversal', '25 delta risk reversal', 'skew', 'tail risk', 'put skew'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_HEAVY_PUT_SKEW', -Infinity, -6, 'institutions paying a heavy premium for downside protection', 'the clearest options-market expression of tail-risk demand', 'bearish'),
      B('STATE_PUT_SKEW', -6, -2, 'a normal equity put skew', 'consistent with routine hedging rather than stress', 'neutral'),
      NEUTRAL('STATE_FLAT_SKEW', -2, 1, 'an unusually flat skew'),
      B('STATE_CALL_SKEW', 1, Infinity, 'institutions paying a premium for upside calls', 'the skew signature of squeeze or event-driven upside positioning', 'bullish'),
    ],
  },
  {
    key: 'bf25_30d',
    label: '25Δ butterfly (30d)',
    shortLabel: 'BF 25Δ',
    group: 'skew',
    unit: 'volpoints',
    description: 'Smile convexity: wing average minus at-the-money.',
    formula: 'BF₂₅ = (σ₂₅c + σ₂₅p)/2 − σ_ATM',
    sqlColumn: 'bf25_30d',
    aliases: ['butterfly', 'smile convexity', 'kurtosis', 'wings'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_FLAT_WINGS', -Infinity, 0.4, 'flat smile wings', 'showing the market prices thin tails', 'neutral'),
      NEUTRAL('STATE_NORMAL_WINGS', 0.4, 2, 'ordinary smile convexity'),
      B('STATE_FAT_WINGS', 2, Infinity, 'fat smile wings', 'showing the market prices a bimodal, event-driven distribution', 'neutral'),
    ],
  },
  {
    key: 'sabr_rho',
    label: 'SABR ρ',
    shortLabel: 'SABR ρ',
    group: 'skew',
    unit: 'ratio',
    description: 'Fitted spot/volatility correlation — the structural source of the skew.',
    formula: 'ρ from the Nelder–Mead fit of Hagan σ_B to the observed smile',
    sqlColumn: 'sabr_rho',
    aliases: ['sabr rho', 'spot vol correlation', 'leverage effect'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_STRONG_LEVERAGE', -Infinity, -0.6, 'a strongly negative spot/vol correlation', 'meaning a decline would be accompanied by a violent volatility expansion', 'bearish'),
      NEUTRAL('STATE_NORMAL_LEVERAGE', -0.6, -0.1, 'an ordinary negative spot/vol correlation'),
      B('STATE_WEAK_LEVERAGE', -0.1, Infinity, 'little or positive spot/vol correlation', 'an unusual structure worth treating with suspicion', 'neutral'),
    ],
  },
  {
    key: 'sabr_nu',
    label: 'SABR ν (vol of vol)',
    shortLabel: 'SABR ν',
    group: 'skew',
    unit: 'ratio',
    description: 'Fitted volatility of volatility — how unstable the surface is.',
    formula: 'ν from the Nelder–Mead fit of Hagan σ_B to the observed smile',
    sqlColumn: 'sabr_nu',
    aliases: ['vol of vol', 'sabr nu', 'volatility of volatility'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_STABLE_SURFACE', -Infinity, 0.4, 'a stable volatility surface', 'so the skew reading is dependable', 'neutral'),
      NEUTRAL('STATE_NORMAL_SURFACE', 0.4, 0.9, 'an ordinary volatility surface'),
      B('STATE_UNSTABLE_SURFACE', 0.9, Infinity, 'an unstable volatility surface', 'meaning the smile itself is likely to reprice before the horizon completes', 'bearish'),
    ],
  },
  {
    key: 'iv_rv_spread',
    label: 'IV − RV spread',
    shortLabel: 'IV−RV',
    group: 'skew',
    unit: 'percent',
    description: 'Implied minus realised volatility — the variance risk premium.',
    formula: '100·(σ_ATM,30d − realisedVol₂₀)',
    sqlColumn: 'iv_rv_spread',
    aliases: ['variance risk premium', 'iv rv spread', 'implied vs realized'],
    inModel: true,
    precision: 1,
    states: [
      B('STATE_IV_CHEAP', -Infinity, -3, 'implied volatility below realised', 'a rare state in which owning options is statistically favourable', 'neutral'),
      NEUTRAL('STATE_FAIR_PREMIUM', -3, 8, 'an ordinary variance risk premium'),
      B('STATE_IV_EXPENSIVE', 8, Infinity, 'implied volatility far above realised', 'showing the options market expects a regime change the tape has not yet delivered', 'neutral'),
    ],
  },
  {
    key: 'vol_term_slope',
    label: 'Vol term-structure slope',
    shortLabel: 'Term slope',
    group: 'skew',
    unit: 'volpoints',
    description: '90-day minus 7-day at-the-money implied volatility.',
    formula: 'σ_ATM,90d − σ_ATM,7d',
    sqlColumn: 'vol_term_slope',
    aliases: ['term structure', 'vol curve', 'contango', 'backwardation'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_BACKWARDATION', -Infinity, -2, 'a backwardated volatility term structure', 'the classic signature of acute near-term event risk or stress', 'bearish'),
      NEUTRAL('STATE_FLAT_TERM', -2, 1, 'a flat volatility term structure'),
      B('STATE_CONTANGO', 1, Infinity, 'an upward-sloping volatility term structure', 'the calm-market default, with no acute near-term event priced', 'bullish'),
    ],
  },
  {
    key: 'put_call_oi_ratio',
    label: 'Put/call open interest',
    shortLabel: 'P/C OI',
    group: 'skew',
    unit: 'ratio',
    description: 'Put open interest divided by call open interest.',
    formula: 'Σ putOI / Σ callOI across the modelled chain',
    sqlColumn: 'put_call_oi_ratio',
    aliases: ['put call ratio', 'open interest ratio', 'positioning'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_CALL_HEAVY', -Infinity, 0.7, 'call-heavy open interest', 'showing crowded upside positioning that can unwind sharply', 'neutral'),
      NEUTRAL('STATE_BALANCED_OI', 0.7, 1.3, 'balanced open interest'),
      B('STATE_PUT_HEAVY', 1.3, Infinity, 'put-heavy open interest', 'a contrarian condition where hedges become fuel for a squeeze', 'bullish'),
    ],
  },
  {
    key: 'put_call_volume_ratio',
    label: 'Put/call volume',
    shortLabel: 'P/C vol',
    group: 'skew',
    unit: 'ratio',
    description: 'Same-session put volume divided by call volume.',
    formula: 'Σ putVolume / Σ callVolume across the modelled chain',
    sqlColumn: 'put_call_volume_ratio',
    aliases: ['put call volume', 'option volume ratio'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_CALL_FLOW', -Infinity, 0.7, 'call-dominated option flow', 'consistent with speculative upside demand', 'bullish'),
      NEUTRAL('STATE_BALANCED_FLOW', 0.7, 1.3, 'balanced option flow'),
      B('STATE_PUT_FLOW', 1.3, Infinity, 'put-dominated option flow', 'consistent with active hedging or directional downside bets', 'bearish'),
    ],
  },

  // ── Alt-data ──────────────────────────────────────────────────────────────
  {
    key: 'alt_composite',
    label: 'Alt-data composite',
    shortLabel: 'Alt composite',
    group: 'altdata',
    unit: 'signed_unit',
    description: 'Evidence-weighted blend of every decayed alternative-data stream.',
    formula: 'Σ (evidenceShare_s · score_s), evidence = Σ decay(age)·authority·confidence',
    sqlColumn: 'alt_composite',
    aliases: ['alternative data', 'alt data score', 'ai sentiment score', 'sentiment'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_STRONGLY_NEGATIVE', -Infinity, -0.4, 'a strongly negative alternative-data consensus', 'with the highest-authority sources agreeing on deterioration', 'bearish'),
      B('STATE_NEGATIVE', -0.4, -0.12, 'a mildly negative alternative-data consensus', 'a modest drag on the thesis', 'bearish'),
      NEUTRAL('STATE_NEUTRAL', -0.12, 0.12, 'a neutral alternative-data consensus'),
      B('STATE_POSITIVE', 0.12, 0.4, 'a mildly positive alternative-data consensus', 'a modest tailwind to the thesis', 'bullish'),
      B('STATE_STRONGLY_POSITIVE', 0.4, Infinity, 'a strongly positive alternative-data consensus', 'with the highest-authority sources agreeing on improvement', 'bullish'),
    ],
  },
  {
    key: 'insider_form4_score',
    label: 'Form 4 insider score',
    shortLabel: 'Insider',
    group: 'altdata',
    unit: 'signed_unit',
    description: 'Decayed net insider transaction signal from SEC Form 4 filings.',
    formula: 'Σ wᵢvᵢ/Σ wᵢ with w = smoothedDecay(age; H = 60d, plateau 5d) × authority 1.0',
    sqlColumn: 'insider_form4_score',
    aliases: ['insider buying', 'form 4', 'insider selling', 'insider transactions'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_INSIDER_SELLING', -Infinity, -0.25, 'net insider distribution on file', 'the highest-authority negative signal in the alternative-data set', 'bearish'),
      NEUTRAL('STATE_NO_INSIDER_SIGNAL', -0.25, 0.25, 'no material insider activity on file'),
      B('STATE_INSIDER_BUYING', 0.25, Infinity, 'net insider accumulation on file', 'the highest-authority positive signal in the alternative-data set, and one that decays over months rather than minutes', 'bullish'),
    ],
  },
  {
    key: 'inst_13f_score',
    label: '13F institutional score',
    shortLabel: '13F',
    group: 'altdata',
    unit: 'signed_unit',
    description: 'Decayed net institutional positioning change from 13F-HR filings.',
    formula: 'Σ wᵢvᵢ/Σ wᵢ with w = smoothedDecay(age; H = 75d, plateau 7d) × authority 1.0',
    sqlColumn: 'inst_13f_score',
    aliases: ['13f', 'institutional ownership', 'smart money', 'fund positioning'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_DISTRIBUTION', -Infinity, -0.2, 'net institutional distribution across reporting funds', 'removing a structural bid from the tape', 'bearish'),
      NEUTRAL('STATE_STABLE_OWNERSHIP', -0.2, 0.2, 'stable institutional ownership'),
      B('STATE_ACCUMULATION', 0.2, Infinity, 'net institutional accumulation across reporting funds', 'adding a structural bid to the tape', 'bullish'),
    ],
  },
  {
    key: 'social_sentiment',
    label: 'Social sentiment',
    shortLabel: 'Social',
    group: 'altdata',
    unit: 'signed_unit',
    description: 'Steeply decayed retail social sentiment, authority-discounted to 0.30.',
    formula: 'Σ wᵢvᵢ/Σ wᵢ with w = 2^(−age/H) × 0.30, H = 30–45 min',
    sqlColumn: 'social_sentiment',
    aliases: ['social sentiment', 'reddit', 'twitter', 'retail sentiment', 'stocktwits'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_BEARISH_CHATTER', -Infinity, -0.3, 'bearish retail chatter', 'a low-authority input that decays within the hour and is often contrarian', 'neutral'),
      NEUTRAL('STATE_QUIET', -0.3, 0.3, 'unremarkable retail chatter'),
      B('STATE_BULLISH_CHATTER', 0.3, Infinity, 'bullish retail chatter', 'a low-authority input that decays within the hour and is often contrarian', 'neutral'),
    ],
  },
  {
    key: 'news_sentiment',
    label: 'News sentiment',
    shortLabel: 'News',
    group: 'altdata',
    unit: 'signed_unit',
    description: 'Decayed newswire tone, authority-weighted 0.60.',
    formula: 'Σ wᵢvᵢ/Σ wᵢ with w = 2^(−age/6h) × 0.60',
    sqlColumn: 'news_sentiment',
    aliases: ['news sentiment', 'headlines', 'newswire', 'media tone'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_NEGATIVE_COVERAGE', -Infinity, -0.25, 'negative news coverage', 'creating headline risk into the horizon', 'bearish'),
      NEUTRAL('STATE_NEUTRAL_COVERAGE', -0.25, 0.25, 'neutral news coverage'),
      B('STATE_POSITIVE_COVERAGE', 0.25, Infinity, 'positive news coverage', 'providing a narrative tailwind', 'bullish'),
    ],
  },
  {
    key: 'options_flow_score',
    label: 'Unusual options flow',
    shortLabel: 'Opt flow',
    group: 'altdata',
    unit: 'signed_unit',
    description: 'Decayed directional signal from large, aggressive option sweeps.',
    formula: 'Σ wᵢvᵢ/Σ wᵢ with w = 2^(−age/3h) × 0.70',
    sqlColumn: 'options_flow_score',
    aliases: ['options flow', 'sweeps', 'unusual options activity', 'smart money flow'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_BEARISH_SWEEPS', -Infinity, -0.25, 'aggressive put sweeps on the tape', 'informed flow positioning for downside', 'bearish'),
      NEUTRAL('STATE_NO_UNUSUAL_FLOW', -0.25, 0.25, 'no unusual option activity'),
      B('STATE_BULLISH_SWEEPS', 0.25, Infinity, 'aggressive call sweeps on the tape', 'informed flow positioning for upside', 'bullish'),
    ],
  },
  {
    key: 'analyst_revision_score',
    label: 'Analyst revision score',
    shortLabel: 'Revisions',
    group: 'altdata',
    unit: 'signed_unit',
    description: 'Decayed sell-side target and estimate revisions.',
    formula: 'Σ wᵢvᵢ/Σ wᵢ with w = smoothedDecay(age; H = 21d, plateau 2d) × 0.75',
    sqlColumn: 'analyst_revision_score',
    aliases: ['analyst revisions', 'price target', 'estimate revisions', 'upgrades'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_DOWNGRADES', -Infinity, -0.2, 'negative sell-side revisions', 'a slow-moving but persistent drag on the multiple', 'bearish'),
      NEUTRAL('STATE_STABLE_ESTIMATES', -0.2, 0.2, 'stable sell-side estimates'),
      B('STATE_UPGRADES', 0.2, Infinity, 'positive sell-side revisions', 'a slow-moving but persistent tailwind to the multiple', 'bullish'),
    ],
  },
  {
    key: 'short_interest_score',
    label: 'Short interest signal',
    shortLabel: 'Short int',
    group: 'altdata',
    unit: 'signed_unit',
    description: 'Decayed short-interest change; positive = shorts covering.',
    formula: 'Σ wᵢvᵢ/Σ wᵢ with w = smoothedDecay(age; H = 14d, plateau 1d) × 0.80',
    sqlColumn: 'short_interest_score',
    aliases: ['short interest', 'short squeeze', 'days to cover', 'borrow'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_SHORTS_BUILDING', -Infinity, -0.2, 'a building short base', 'bearish on its face, but also latent squeeze fuel', 'bearish'),
      NEUTRAL('STATE_STABLE_SHORTS', -0.2, 0.2, 'a stable short base'),
      B('STATE_SHORTS_COVERING', 0.2, Infinity, 'shorts actively covering', 'a mechanical bid independent of fundamentals', 'bullish'),
    ],
  },
  {
    key: 'structural_alt_score',
    label: 'Structural alt-data',
    shortLabel: 'Structural',
    group: 'altdata',
    unit: 'signed_unit',
    description: 'Blended slow alternative data: hiring, web traffic, supply chain, patents.',
    formula: 'evidence-weighted mean of the job_postings, web_traffic, supply_chain and patent streams',
    sqlColumn: 'structural_alt_score',
    aliases: ['hiring', 'web traffic', 'supply chain', 'patents', 'fundamental momentum'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_DETERIORATING', -Infinity, -0.2, 'deteriorating operating fundamentals in the alternative data', 'a signal that leads reported results by quarters', 'bearish'),
      NEUTRAL('STATE_STEADY', -0.2, 0.2, 'steady operating fundamentals'),
      B('STATE_IMPROVING', 0.2, Infinity, 'improving operating fundamentals in the alternative data', 'a signal that leads reported results by quarters', 'bullish'),
    ],
  },
  {
    key: 'alt_evidence',
    label: 'Alt-data evidence weight',
    shortLabel: 'Alt evidence',
    group: 'altdata',
    unit: 'count',
    description: 'Total live, decay-and-authority-weighted evidence behind the composite.',
    formula: 'Σ over all events of decay(age)·authority·confidence',
    sqlColumn: 'alt_evidence',
    aliases: ['evidence', 'data coverage', 'alt data volume'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_THIN_COVERAGE', -Infinity, 1.5, 'thin alternative-data coverage', 'so the alternative-data block should carry little weight here', 'neutral'),
      NEUTRAL('STATE_ADEQUATE_COVERAGE', 1.5, 8, 'adequate alternative-data coverage'),
      B('STATE_RICH_COVERAGE', 8, Infinity, 'dense alternative-data coverage', 'so the alternative-data block is unusually well supported', 'neutral'),
    ],
  },

  // ── Relative / cross-sectional ────────────────────────────────────────────
  {
    key: 'rel_strength_20d',
    label: 'Relative strength (20d)',
    shortLabel: 'RS 20d',
    group: 'relative',
    unit: 'percent',
    description: 'Twenty-bar return minus the benchmark return.',
    formula: '100·(r₂₀(symbol) − r₂₀(SPY))',
    sqlColumn: 'rel_strength_20d',
    aliases: ['relative strength', 'outperformance', 'vs spy', 'alpha'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_LAGGING', -Infinity, -5, 'material underperformance against the index', 'placing the name in the weak tail of the cross-section', 'bearish'),
      NEUTRAL('STATE_IN_LINE', -5, 5, 'performance in line with the index'),
      B('STATE_LEADING', 5, Infinity, 'material outperformance against the index', 'placing the name in the strong tail of the cross-section', 'bullish'),
    ],
  },
  {
    key: 'beta_60',
    label: 'Beta (60d)',
    shortLabel: 'β 60d',
    group: 'relative',
    unit: 'ratio',
    description: 'Rolling 60-bar beta to the benchmark.',
    formula: 'β = cov(r, r_bench)/var(r_bench) over 60 bars',
    sqlColumn: 'beta_60',
    aliases: ['beta', 'market sensitivity', 'systematic risk'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_DEFENSIVE', -Infinity, 0.7, 'a defensive beta profile', 'so the position is largely independent of index direction', 'neutral'),
      NEUTRAL('STATE_MARKET_BETA', 0.7, 1.3, 'a market-like beta profile'),
      B('STATE_HIGH_BETA', 1.3, Infinity, 'a high-beta profile', 'so index direction will dominate stock-specific edge', 'neutral'),
    ],
  },
  {
    key: 'idio_alpha_60',
    label: 'Idiosyncratic α (60d)',
    shortLabel: 'Idio α',
    group: 'relative',
    unit: 'bps',
    description: 'Beta-adjusted excess return per bar, in basis points.',
    formula: '10 000·(mean(r) − β·mean(r_bench)) over 60 bars',
    sqlColumn: 'idio_alpha_60',
    aliases: ['idiosyncratic alpha', 'excess return', 'stock specific'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_NEGATIVE_ALPHA', -Infinity, -3, 'negative beta-adjusted excess return', 'meaning the name has been destroying value relative to its risk', 'bearish'),
      NEUTRAL('STATE_NO_ALPHA', -3, 3, 'no beta-adjusted excess return'),
      B('STATE_POSITIVE_ALPHA', 3, Infinity, 'positive beta-adjusted excess return', 'the cleanest evidence of genuine stock-specific edge', 'bullish'),
    ],
  },
  {
    key: 'corr_bench_60',
    label: 'Correlation to benchmark (60d)',
    shortLabel: 'Corr 60d',
    group: 'relative',
    unit: 'ratio',
    description: 'Rolling 60-bar return correlation to the benchmark.',
    formula: 'ρ(r, r_bench) over 60 bars',
    sqlColumn: 'corr_bench_60',
    aliases: ['correlation', 'diversification', 'index correlation'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_DECORRELATED', -Infinity, 0.35, 'low correlation to the index', 'so the position adds genuine diversification', 'bullish'),
      NEUTRAL('STATE_NORMAL_CORR', 0.35, 0.75, 'ordinary index correlation'),
      B('STATE_HIGHLY_CORRELATED', 0.75, Infinity, 'high correlation to the index', 'so the position is close to a leveraged index bet', 'neutral'),
    ],
  },
  {
    key: 'sector_rel_strength',
    label: 'Sector relative strength',
    shortLabel: 'Sector RS',
    group: 'relative',
    unit: 'percent',
    description: 'Twenty-bar return minus the equal-weighted sector return.',
    formula: '100·(r₂₀(symbol) − mean r₂₀(sector peers))',
    sqlColumn: 'sector_rel_strength',
    aliases: ['sector relative strength', 'peer comparison', 'industry leader'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_SECTOR_LAGGARD', -Infinity, -4, 'underperformance against sector peers', 'so the weakness is stock-specific rather than sector-wide', 'bearish'),
      NEUTRAL('STATE_SECTOR_INLINE', -4, 4, 'performance in line with sector peers'),
      B('STATE_SECTOR_LEADER', 4, Infinity, 'outperformance against sector peers', 'the cohort that historically continues to lead', 'bullish'),
    ],
  },

  // ── Volume ────────────────────────────────────────────────────────────────
  {
    key: 'rel_volume_20',
    label: 'Relative volume (20)',
    shortLabel: 'RVOL',
    group: 'volume',
    unit: 'ratio',
    description: 'Current volume divided by its 20-bar average.',
    formula: 'volume / SMA(volume, 20)',
    sqlColumn: 'rel_volume_20',
    aliases: ['relative volume', 'rvol', 'volume surge', 'unusual volume'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_DRIED_UP', -Infinity, 0.6, 'volume well below normal', 'so any price move lacks participation and should be distrusted', 'bearish'),
      NEUTRAL('STATE_NORMAL_VOLUME', 0.6, 1.5, 'ordinary participation'),
      B('STATE_ELEVATED_VOLUME', 1.5, 3, 'elevated participation', 'confirming that real size is behind the move', 'bullish'),
      B('STATE_VOLUME_SURGE', 3, Infinity, 'a volume surge', 'the participation signature of an institutional repositioning event', 'bullish'),
    ],
  },
  {
    key: 'obv_slope_20',
    label: 'OBV slope (20)',
    shortLabel: 'OBV slope',
    group: 'volume',
    unit: 'ratio',
    description: 'Normalised slope of On-Balance Volume over 20 bars.',
    formula: 'β of OBV on bar index over 20 bars, divided by mean|OBV|',
    sqlColumn: 'obv_slope_20',
    aliases: ['obv', 'on balance volume', 'accumulation'],
    inModel: true,
    precision: 4,
    states: [
      B('STATE_DISTRIBUTION', -Infinity, -0.01, 'volume-weighted distribution', 'showing supply leaving on down-ticks', 'bearish'),
      NEUTRAL('STATE_NEUTRAL_FLOW', -0.01, 0.01, 'neutral volume flow'),
      B('STATE_ACCUMULATION', 0.01, Infinity, 'volume-weighted accumulation', 'showing demand arriving on up-ticks', 'bullish'),
    ],
  },
  {
    key: 'cmf_20',
    label: 'Chaikin money flow (20)',
    shortLabel: 'CMF 20',
    group: 'volume',
    unit: 'signed_unit',
    description: 'Volume-weighted close location over 20 bars.',
    formula: 'Σ(((2C − L − H)/(H − L))·V) / ΣV over 20 bars',
    sqlColumn: 'cmf_20',
    aliases: ['chaikin money flow', 'cmf', 'money flow multiplier'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_SELLING_PRESSURE', -Infinity, -0.1, 'volume concentrating at the lows of bars', 'the footprint of persistent selling pressure', 'bearish'),
      NEUTRAL('STATE_BALANCED_PRESSURE', -0.1, 0.1, 'volume spread evenly across bar ranges'),
      B('STATE_BUYING_PRESSURE', 0.1, Infinity, 'volume concentrating at the highs of bars', 'the footprint of persistent buying pressure', 'bullish'),
    ],
  },
  {
    key: 'adv_ratio',
    label: 'Volume vs 30-day ADV',
    shortLabel: 'vs ADV',
    group: 'volume',
    unit: 'ratio',
    description: 'Session volume relative to the 30-day average daily volume.',
    formula: 'volume / ADV₃₀',
    sqlColumn: 'adv_ratio',
    aliases: ['average daily volume', 'adv', 'liquidity ratio'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_BELOW_ADV', -Infinity, 0.7, 'volume below the 30-day average', 'leaving less room before the 5%-of-ADV limiter binds', 'neutral'),
      NEUTRAL('STATE_AT_ADV', 0.7, 1.4, 'volume at the 30-day average'),
      B('STATE_ABOVE_ADV', 1.4, Infinity, 'volume above the 30-day average', 'widening the executable size before the liquidity limiter binds', 'bullish'),
    ],
  },
  {
    key: 'dollar_volume_z',
    label: 'Dollar volume z-score',
    shortLabel: '$Vol z',
    group: 'volume',
    unit: 'zscore',
    description: 'Standardised dollar volume against its own 60-bar history.',
    formula: '(price·volume − μ₆₀)/σ₆₀',
    sqlColumn: 'dollar_volume_z',
    aliases: ['dollar volume', 'notional volume', 'turnover'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_QUIET_TURNOVER', -Infinity, -1, 'unusually low notional turnover', 'so the tape is unlikely to sustain a directional move', 'bearish'),
      NEUTRAL('STATE_NORMAL_TURNOVER', -1, 1.5, 'ordinary notional turnover'),
      B('STATE_HEAVY_TURNOVER', 1.5, Infinity, 'unusually heavy notional turnover', 'the notional footprint of a genuine institutional event', 'bullish'),
    ],
  },

  // ── Regime ────────────────────────────────────────────────────────────────
  {
    key: 'hurst_100',
    label: 'Hurst exponent (100)',
    shortLabel: 'Hurst',
    group: 'regime',
    unit: 'ratio',
    description: 'Rescaled-range Hurst exponent; 0.5 = random walk.',
    formula: 'β of log(R/S) on log(n) across sub-window sizes',
    sqlColumn: 'hurst_100',
    aliases: ['hurst', 'persistence', 'trending or mean reverting', 'fractal dimension'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_ANTI_PERSISTENT', -Infinity, 0.45, 'an anti-persistent series', 'the statistical regime in which mean-reversion models dominate', 'neutral'),
      NEUTRAL('STATE_RANDOM_WALK', 0.45, 0.55, 'a series indistinguishable from a random walk'),
      B('STATE_PERSISTENT', 0.55, Infinity, 'a persistent, trending series', 'the statistical regime in which continuation models dominate', 'neutral'),
    ],
  },
  {
    key: 'adf_stat_120',
    label: 'ADF statistic (120)',
    shortLabel: 'ADF',
    group: 'regime',
    unit: 'zscore',
    description: 'Augmented Dickey–Fuller τ statistic; more negative means more stationary.',
    formula: 'γ̂/se(γ̂) from Δyₜ = γyₜ₋₁ + δΔyₜ₋₁ + ε',
    sqlColumn: 'adf_stat_120',
    aliases: ['adf', 'stationarity', 'unit root', 'dickey fuller'],
    inModel: true,
    precision: 2,
    states: [
      B('STATE_STATIONARY', -Infinity, -2.86, 'a statistically stationary series at the 5% level', 'validating the mean-reversion framework for this name', 'neutral'),
      B('STATE_WEAKLY_STATIONARY', -2.86, -1.9, 'weak evidence of stationarity', 'making the reversion thesis plausible but unconfirmed', 'neutral'),
      B('STATE_UNIT_ROOT', -1.9, Infinity, 'a series with a unit root', 'so reversion targets have no statistical anchor and trend models are preferred', 'neutral'),
    ],
  },
  {
    key: 'vol_percentile_252',
    label: 'Volatility percentile (252)',
    shortLabel: 'Vol %ile',
    group: 'regime',
    unit: 'probability',
    description: 'Where current realised volatility sits within its own annual history.',
    formula: 'rank(realisedVol₂₀) / n over the last 252 bars',
    sqlColumn: 'vol_percentile_252',
    aliases: ['volatility percentile', 'vol regime', 'volatility rank'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_VOL_TROUGH', -Infinity, 0.2, 'volatility in the bottom fifth of its annual range', 'a compressed regime that historically expands', 'neutral'),
      NEUTRAL('STATE_VOL_NORMAL', 0.2, 0.8, 'volatility in its normal annual range'),
      B('STATE_VOL_PEAK', 0.8, Infinity, 'volatility in the top fifth of its annual range', 'a stressed regime where position sizes must shrink for constant risk', 'bearish'),
    ],
  },
  {
    key: 'regime_trend_score',
    label: 'Regime trend score',
    shortLabel: 'Regime score',
    group: 'regime',
    unit: 'signed_unit',
    description: 'Composite trend-versus-reversion score from Hurst, ADF and ADX.',
    formula: 'tanh(2·(hurst − 0.5) + adx/60 + max(0, adf + 2)/3)',
    sqlColumn: 'regime_trend_score',
    aliases: ['regime', 'market regime', 'trend regime'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_REVERSION_REGIME', -Infinity, -0.25, 'a mean-reverting regime', 'in which continuation entries have historically bled', 'neutral'),
      NEUTRAL('STATE_MIXED_REGIME', -0.25, 0.25, 'a mixed regime'),
      B('STATE_TREND_REGIME', 0.25, Infinity, 'a trending regime', 'in which reversion entries have historically bled', 'neutral'),
    ],
  },
  {
    key: 'liquidity_score',
    label: 'Liquidity score',
    shortLabel: 'Liquidity',
    group: 'regime',
    unit: 'probability',
    description: 'Composite executability score from spread, depth, ADV and Amihud.',
    formula: 'mean of the four percentile-normalised liquidity components',
    sqlColumn: 'liquidity_score',
    aliases: ['liquidity', 'executability', 'tradability'],
    inModel: true,
    precision: 3,
    states: [
      B('STATE_POOR_LIQUIDITY', -Infinity, 0.3, 'poor executability', 'so realised slippage will consume much of the modelled edge', 'bearish'),
      NEUTRAL('STATE_ADEQUATE_LIQUIDITY', 0.3, 0.7, 'adequate executability'),
      B('STATE_EXCELLENT_LIQUIDITY', 0.7, Infinity, 'excellent executability', 'so the modelled edge survives transaction costs', 'bullish'),
    ],
  },
  {
    key: 'minutes_since_open',
    label: 'Minutes since open',
    shortLabel: 'Session min',
    group: 'regime',
    unit: 'count',
    description: 'Minutes elapsed in the regular session — an intraday seasonality control.',
    formula: 'clock(New York) − 09:30, clamped to the session length',
    sqlColumn: 'minutes_since_open',
    aliases: ['time of day', 'session time', 'minutes since open'],
    inModel: true,
    precision: 0,
    states: [
      B('STATE_OPENING_DRIVE', -Infinity, 30, 'the opening thirty minutes', 'the highest-volatility, widest-spread window of the session', 'neutral'),
      B('STATE_MORNING', 30, 150, 'the morning trend window', 'when institutional participation is highest', 'neutral'),
      B('STATE_MIDDAY_LULL', 150, 300, 'the midday liquidity lull', 'when breakouts have their lowest follow-through rate', 'neutral'),
      B('STATE_CLOSING_DRIVE', 300, Infinity, 'the closing drive', 'when index rebalancing and MOC imbalances dominate the tape', 'neutral'),
    ],
  },
  {
    key: 'day_of_week',
    label: 'Day of week',
    shortLabel: 'Weekday',
    group: 'regime',
    unit: 'count',
    description: 'Weekday index (1 = Monday) — a calendar seasonality control.',
    formula: 'ISO weekday of the New York session date',
    sqlColumn: 'day_of_week',
    aliases: ['day of week', 'weekday', 'seasonality'],
    inModel: true,
    precision: 0,
    states: [
      B('STATE_MONDAY', -Infinity, 1.5, 'a Monday session', 'when weekend information is repriced in the first hour', 'neutral'),
      B('STATE_MIDWEEK', 1.5, 4.5, 'a midweek session', 'the most statistically ordinary part of the week', 'neutral'),
      B('STATE_FRIDAY', 4.5, Infinity, 'a Friday session', 'when option expiry pinning and weekend risk reduction distort the tape', 'neutral'),
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
//  Registry helpers
// ─────────────────────────────────────────────────────────────────────────────

const BY_KEY = new Map(FEATURE_DEFINITIONS.map((f) => [f.key, f]));

/** Ordered keys of the model input vector — the single source of column order. */
export const MODEL_FEATURE_KEYS: string[] = FEATURE_DEFINITIONS.filter((f) => f.inModel).map((f) => f.key);

export const MODEL_FEATURE_COUNT = MODEL_FEATURE_KEYS.length;

export function featureDefinition(key: string): FeatureDefinition | undefined {
  return BY_KEY.get(key);
}

export function requireFeature(key: string): FeatureDefinition {
  const f = BY_KEY.get(key);
  if (!f) throw new Error(`Unknown feature key: ${key}`);
  return f;
}

export function featuresInGroup(group: FeatureGroup): FeatureDefinition[] {
  return FEATURE_DEFINITIONS.filter((f) => f.group === group);
}

export const FEATURE_GROUPS: FeatureGroup[] = [
  'momentum',
  'trend',
  'volatility',
  'meanreversion',
  'microstructure',
  'skew',
  'altdata',
  'relative',
  'volume',
  'regime',
];

export const FEATURE_GROUP_LABELS: Record<FeatureGroup, string> = {
  momentum: 'Momentum & oscillators',
  trend: 'Trend structure',
  volatility: 'Volatility',
  meanreversion: 'Continuous-time mean reversion',
  microstructure: 'Order-book microstructure',
  skew: 'Options volatility skew',
  altdata: 'Alternative data',
  relative: 'Cross-sectional & relative',
  volume: 'Volume & participation',
  regime: 'Regime & seasonality',
};

/** Resolves the state band a raw value falls into. */
export function resolveState(definition: FeatureDefinition, value: number): FeatureState {
  for (const band of definition.states) {
    if (value >= band.min && value < band.max) return band;
  }
  return definition.states[definition.states.length - 1] as FeatureState;
}

/** Formats a raw value in its native unit for display. */
export function formatFeatureValue(definition: FeatureDefinition, value: number): string {
  if (!Number.isFinite(value)) return '—';
  const n = value.toFixed(definition.precision);
  switch (definition.unit) {
    case 'percent':
      return `${n}%`;
    case 'bps':
      return `${n} bp`;
    case 'volpoints':
      return `${n} vp`;
    case 'probability':
      return `${(value * 100).toFixed(1)}%`;
    case 'zscore':
      return `${value >= 0 ? '+' : ''}${n}σ`;
    case 'signed_unit':
      return `${value >= 0 ? '+' : ''}${n}`;
    case 'bars':
      return Number.isFinite(value) ? `${n} bars` : '∞';
    case 'currency':
      return `$${Number(n).toLocaleString('en-US')}`;
    case 'shares':
      return Number(value).toLocaleString('en-US');
    case 'index_0_100':
    case 'ratio':
    case 'count':
    default:
      return n;
  }
}
